root: true

extends: [airbnb-base, plugin:prettier/recommended]

#plugins: [import, json, promise, mocha]
plugins: [import, json, promise]

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: {}

# settings:
#   import/resolver:
#     node:
#       extensions: [.js, .mjs]

rules:
  # arrow-body-style: [error, always]
  # arrow-parens: off
  import/extensions: [error, always, { js: never, mjs: never }]
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ['test/**', '**/*.test.js']
      optionalDependencies: false
  import/prefer-default-export: [off, never]
  linebreak-style: off
  no-console: off
  no-param-reassign: [error, { props: false }]
  no-use-before-define: [error, nofunc]
  # we are using code with tons of promise/then semantics and callbacks, so
  # allow it for now!
  promise/prefer-await-to-callbacks: off
  promise/prefer-await-to-then: off
  # sort-keys: error

env:
  node: true
  # mocha: true
# overrides:
#   files: ['test/**', '**/*.test.js']
#   rules:
#     # chai has function-less ".exists" and ".true" properties that trigger the
#     # no-unused-expressions rule
#     no-unused-expressions: off
